import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Auction from "@/components/auction";
import News from "@/components/news";
import Brands from "@/components/brands";
import Products from "@/components/product";
import Sales from "@/components/sales";
import Useful from "@/components/usefil";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Auction />
        <News />
        <Products />
        <Sales />
        <Useful />
        <Brands />
        <Footer />
      </body>
    </html>
  );
}
